- name: Instala pacotes para suporte a PHP no Apache em Distribuições Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    state: present
    update_cache: true
    pkg:
    - apache2
    - php7.4
    - php7.4-mysql
    - php-memcache
  register: php_packages_ubuntu_installed
  notify:
    - Restart Apache
- name: Instala pacotes para suporte a PHP no Apache em Distribuições RedHat/CentOS
  when: ansible_os_family == "RedHat"
  yum:
    state: present
    pkg:
    - epel-release
    - httpd
    - php
    - php-mysqlnd
  register: php_packages_centos_installed
  notify:
    - Restart Httpd
